# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title ass
#' @description
#'   Function generates all possible 0-1 assignment
#' vectors of 2n survey participants in such a way that exactly n of them are assigned to group 0 control
#' and the other n ones are assigned to group 1 treatment.
#'
#' @param r - an integer
#' @return a matrix with 2n columns and an appropriate number of rows.
#'
#' @export
ass <- function(r) {
    .Call('mypackage_ass', PACKAGE = 'mypackage', r)
}

#' @title mode
#' @description
#'   Function returs a value that appears most often in a set of data.
#'
#' @param x - an integer vector
#' @return The most frequently occuring value.
#'
#' @export
mode <- function(x) {
    .Call('mypackage_mode', PACKAGE = 'mypackage', x)
}

#' @title simplify2array
#' @description
#'   Function mimics behavior of simplify2array from base when higher = T
#'
#' @param x - List of numeric vectors
#' @return Simplified matrix
#'
#' @export
simplify2array <- function(x) {
    .Call('mypackage_simplify2array', PACKAGE = 'mypackage', x)
}

